base_url = "https://anemone.pages.dev"
description = "A minimalist Zola theme that prioritizes clean CSS and avoids heavy JavaScript. Enjoy a seamless user experience with lightning-fast load times. Let your content take center stage in a clutter-free, elegant design that enhances readability. Responsive and efficient, anemone brings focus to your ideas."
theme = "anemone"
compile_sass = true
minify_html = false
generate_feed = true

default_language = "en"

